### ISSUE TITLE
Stack overflow error

### ISSUE THREAD

**Issue by yarensonmez** [VictorSeven/IsingModel#1]
I use Visual Studio 2019. When I tried to run for the L value 128, 256, 512 etc. , it gives a stack overflow error. How can I handle with this error for bigger L values?

**Comment by VictorSeven** [comment]
The code has the Wolff algorithm implemented, which computes spin clusters using a recursive function. If the recursive function is called too many times, it throws a stack overflow. In theory, it should work perfectly even for larger sizes (I did myself up to L=512 and it runs just fine). This was compiling with g++, in a 4GB RAM computer. It is possible that the linker in VS2019 has a very limited stack size, which you can increase manually, allowing the function to allocate more recursive memory. 

However, I got some reports of Stack Overflows, but that was due to some people trying to parallelize the code. This increases a lot the number of calls to the recursive function, causing the overflow. The (recursive) Wolff algorithm, of course, is _not_ meant to be run in parallel!
